/* Generated by cbindgen - DO NOT EDIT BY HAND.
 * Regenerate with `cargo xtask capi` (crates/dstu-core-capi/cbindgen.toml).
 *
 * C ABI for dstu-core (Ukrainian DSTU cryptographic standards - Kalyna, Kupyna, Strumok, DSTU
 * 4145). Pre-release and provisional - see docs/SECURITY.md and docs/DECISIONS.md in the project
 * repository (https://github.com/user137/uacrypt) for the full threat model and per-construction
 * status. */

#ifndef DSTU_CORE_H
#define DSTU_CORE_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#define DSTU_AUTH_KEY_BYTES 32

#define DSTU_AUTH_TAG_BYTES 32

#define DSTU_BOX512_SECRETKEY_BYTES 64

#define DSTU_BOX512_PUBLICKEY_BYTES 64

/**
 * `dstu9041_ciphertext (256) || secretstream_header (32) || tag (16)` - the fixed part of
 * `seal`'s wire format (`crypto_box512`'s own module doc), added to `message_len` for `seal`'s
 * required output capacity, and the exact minimum length `open` accepts.
 */
#define DSTU_BOX512_SEAL_OVERHEAD 304

#define DSTU_BOX_SECRETKEY_BYTES 32

#define DSTU_BOX_PUBLICKEY_BYTES 32

/**
 * `dstu9041_ciphertext (128) || secretstream_header (32) || tag (16)` - the fixed part of
 * `seal`'s wire format (`crypto_box`'s own module doc), added to `message_len` for `seal`'s
 * required output capacity, and the exact minimum length `open` accepts.
 */
#define DSTU_BOX_SEAL_OVERHEAD 176

#define DSTU_GENERICHASH_256_BYTES 32

#define DSTU_GENERICHASH_512_BYTES 64

#define DSTU_KDF_KEY_BYTES 32

#define DSTU_KDF_CONTEXT_BYTES 8

#define DSTU_KDF_SUBKEY_BYTES 32

/**
 * Fixed buffer size for a PHC string produced by `dstu_pwhash_hash_password` - matches
 * libsodium's own `crypto_pwhash_STRBYTES` value exactly (see `docs/DECISIONS.md` D-148 point 3
 * for the hand-counted worst-case-length justification).
 */
#define DSTU_PWHASH_STRBYTES 128

#define DSTU_SECRETBOX_KEY_BYTES 32

/**
 * 32-byte nonce + 16-byte tag.
 */
#define DSTU_SECRETBOX_OVERHEAD 48

#define DSTU_SECRETSTREAM_KEY_BYTES 32

#define DSTU_SECRETSTREAM_HEADER_BYTES 32

#define DSTU_SECRETSTREAM_TAG_BYTES 16

#define DSTU_SIGN_PRIVATE_KEY_BYTES 21

#define DSTU_SIGN_PUBLIC_KEY_BYTES 42

#define DSTU_SIGN_SIGNATURE_BYTES 42

#define DSTU_SIGN_DIGEST_BYTES 32

#define DSTU_SIGN257_PRIVATE_KEY_BYTES 33

#define DSTU_SIGN257_PUBLIC_KEY_BYTES 66

#define DSTU_SIGN257_SIGNATURE_BYTES 66

#define DSTU_SIGN257_DIGEST_BYTES 32

#define DSTU_STREAM_KEY_BYTES 32

/**
 * IV only - no tag, this primitive is unauthenticated by design.
 */
#define DSTU_STREAM_OVERHEAD 32

/**
 * Status/error code returned by most fallible functions in this crate's C ABI.
 */
typedef enum {
  DSTU_OK = 0,
  /**
   * OS CSPRNG failure (`dstu_core::randombytes::RandomError`).
   */
  DSTU_ERR_RANDOM = 1,
  /**
   * AEAD/MAC authentication failed: wrong key, or tampered ciphertext/tag/nonce/header.
   */
  DSTU_ERR_TAG_MISMATCH = 2,
  /**
   * Input shorter than the minimum possible valid output (e.g. below `crypto_secretbox`'s
   * nonce+tag overhead).
   */
  DSTU_ERR_TRUNCATED = 3,
  /**
   * An exact-match length requirement was violated (`crypto_secretstream` push/pull).
   */
  DSTU_ERR_INVALID_LENGTH = 4,
  /**
   * The caller-supplied output buffer's declared capacity is insufficient - checked before any
   * crypto work runs, so a caller never gets a partial write.
   */
  DSTU_ERR_BUFFER_TOO_SMALL = 5,
  /**
   * `crypto_secretstream`: `tag_byte` isn't one of the four valid values.
   */
  DSTU_ERR_UNKNOWN_TAG = 6,
  /**
   * A `crypto_secretstream` push/pull state, or a Kupyna hasher, was already finalized.
   */
  DSTU_ERR_FINALIZED = 7,
  /**
   * `dstu_selftest()`'s own known-answer self-check failed.
   */
  DSTU_ERR_SELFTEST_FAILED = 8,
  /**
   * `crypto_pwhash`'s internal Argon2/PHC-encoding failure - not expected in practice.
   */
  DSTU_ERR_HASH_ERROR = 9,
  /**
   * e.g. a DSTU 4145 signing-key scalar that is zero or greater than or equal to the curve
   * order.
   */
  DSTU_ERR_INVALID_KEY = 10,
  /**
   * A required pointer argument was NULL (or NULL together with a nonzero declared length).
   */
  DSTU_ERR_NULL_POINTER = 11,
  /**
   * An internal panic was caught at the FFI boundary - should never happen in correct code. See
   * this crate's top-level doc comment for why every exported function is wrapped in
   * `catch_unwind`.
   */
  DSTU_ERR_PANIC = 12,
} DstuStatus;

/**
 * Argon2id cost preset - mirrors libsodium's own named `OPSLIMIT`/`MEMLIMIT_*` constants.
 */
typedef enum {
  DSTU_PWHASH_INTERACTIVE = 0,
  DSTU_PWHASH_MODERATE = 1,
  DSTU_PWHASH_SENSITIVE = 2,
} DstuPwhashStrength;

/**
 * A chunk's role in the stream - byte values match libsodium's own encoding, see the wrapped
 * Rust module's doc comment.
 */
typedef enum {
  DSTU_TAG_MESSAGE = 0,
  DSTU_TAG_PUSH = 1,
  DSTU_TAG_REKEY = 2,
  DSTU_TAG_FINAL = 3,
} DstuTag;

/**
 * Opaque `crypto_auth` key handle. `dstu_auth_key_free`'s `Box::from_raw` fires the wrapped
 * `Key`'s own `Zeroize`-on-`Drop` impl.
 */
typedef struct DstuAuthKey DstuAuthKey;

/**
 * Opaque `crypto_box512` public-key handle.
 */
typedef struct DstuBox512PublicKey DstuBox512PublicKey;

/**
 * Opaque `crypto_box512` secret-key handle. `dstu_box512_secretkey_free`'s `Box::from_raw` fires
 * the wrapped `SecretKey`'s own `Zeroize`-on-`Drop` impl.
 */
typedef struct DstuBox512SecretKey DstuBox512SecretKey;

/**
 * Opaque `crypto_box` public-key handle.
 */
typedef struct DstuBoxPublicKey DstuBoxPublicKey;

/**
 * Opaque `crypto_box` secret-key handle. `dstu_box_secretkey_free`'s `Box::from_raw` fires the
 * wrapped `SecretKey`'s own `Zeroize`-on-`Drop` impl.
 */
typedef struct DstuBoxSecretKey DstuBoxSecretKey;

/**
 * Opaque `crypto_kdf` master-key handle. `dstu_kdf_master_key_free`'s `Box::from_raw` fires the
 * wrapped `MasterKey`'s own `Zeroize`-on-`Drop` impl.
 */
typedef struct DstuKdfMasterKey DstuKdfMasterKey;

/**
 * Opaque streaming Kupyna-256 hasher handle.
 */
typedef struct DstuKupyna256Hasher DstuKupyna256Hasher;

/**
 * Opaque streaming Kupyna-512 hasher handle. Same shape as [`DstuKupyna256Hasher`].
 */
typedef struct DstuKupyna512Hasher DstuKupyna512Hasher;

/**
 * Opaque pull-side (decrypting) stream-state handle.
 */
typedef struct DstuPullState DstuPullState;

/**
 * Opaque push-side (encrypting) stream-state handle.
 */
typedef struct DstuPushState DstuPushState;

/**
 * Opaque `crypto_secretbox` key handle. `dstu_secretbox_key_free`'s `Box::from_raw` fires the
 * wrapped `SecretKey`'s own `Zeroize`-on-`Drop` impl.
 */
typedef struct DstuSecretboxKey DstuSecretboxKey;

/**
 * Opaque `crypto_secretstream` master-key handle.
 */
typedef struct DstuSecretstreamKey DstuSecretstreamKey;

/**
 * Opaque signing-key handle. `dstu_sign_key_free`'s `Box::from_raw` fires the wrapped
 * `SigningKey`'s own `Zeroize`-on-`Drop` impl.
 */
typedef struct DstuSigningKey DstuSigningKey;

/**
 * Opaque signing-key handle. `dstu_sign257_key_free`'s `Box::from_raw` fires the wrapped
 * `SigningKey`'s own `Zeroize`-on-`Drop` impl.
 */
typedef struct DstuSigningKey257 DstuSigningKey257;

/**
 * Opaque `crypto_stream` key handle. `dstu_stream_key_free`'s `Box::from_raw` fires the wrapped
 * `Key`'s own `Zeroize`-on-`Drop` impl.
 */
typedef struct DstuStreamKey DstuStreamKey;

/**
 * Opaque verifying-key (public key) handle.
 */
typedef struct DstuVerifyingKey DstuVerifyingKey;

/**
 * Opaque verifying-key (public key) handle.
 */
typedef struct DstuVerifyingKey257 DstuVerifyingKey257;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Generates a fresh key from the OS CSPRNG. Returns `DSTU_OK` (writing `*out`) or
 * `DSTU_ERR_RANDOM`/`DSTU_ERR_NULL_POINTER`.
 *
 * # Safety
 *
 * `out` must be a valid, non-null pointer to a `*mut DstuAuthKey`.
 */
 DstuStatus dstu_auth_key_generate(DstuAuthKey **out);

/**
 * Builds a key from exactly `DSTU_AUTH_KEY_BYTES` bytes. Infallible for a correct call; returns
 * NULL if `key` is NULL (a misuse case with no `DstuStatus` channel to report through here).
 *
 * # Safety
 *
 * `key` must be valid for reads of `DSTU_AUTH_KEY_BYTES` bytes when non-null.
 */
 DstuAuthKey *dstu_auth_key_from_bytes(const uint8_t *key);

/**
 * Copies the key's `DSTU_AUTH_KEY_BYTES`-byte encoding into `out`. A NULL `key`/`out` is a no-op.
 *
 * # Safety
 *
 * `out` must be valid for writes of `DSTU_AUTH_KEY_BYTES` bytes when non-null.
 */
 void dstu_auth_key_bytes(const DstuAuthKey *key, uint8_t *out);

/**
 * Frees a key. NULL is a no-op, matching `free()`'s own convention.
 *
 * # Safety
 *
 * `key` must be either NULL or a pointer previously returned by `dstu_auth_key_generate`/
 * `dstu_auth_key_from_bytes`, not already freed - freeing an already-freed pointer is undefined behavior, not merely unsupported; this fn cannot detect or reject it.
 */

void dstu_auth_key_free(DstuAuthKey *key);

/**
 * Computes the MAC of `message` under `key` - infallible. A NULL `key`/`tag_out`, or a NULL
 * `message` with `message_len > 0`, is a no-op (leaves `tag_out` unwritten).
 *
 * # Safety
 *
 * `message` must be valid for reads of `message_len` bytes when non-null and `message_len > 0`;
 * `tag_out` must be valid for writes of `DSTU_AUTH_TAG_BYTES` bytes when non-null.
 */

void dstu_auth(const DstuAuthKey *key,
               const uint8_t *message,
               size_t message_len,
               uint8_t *tag_out);

/**
 * Verifies `tag` against `message` under `key`. Returns `DSTU_OK` or `DSTU_ERR_TAG_MISMATCH` on
 * an actual verification failure. `DSTU_ERR_NULL_POINTER` for a NULL `key`/`tag`, or a NULL
 * `message` with `message_len > 0` - consistent with this crate's own null-hygiene convention
 * (`lib.rs`'s doc comment): a `DstuStatus` channel exists here, so a NULL pointer is reported
 * through it rather than folded into `DSTU_ERR_TAG_MISMATCH`.
 *
 * # Safety
 *
 * `message` must be valid for reads of `message_len` bytes when non-null and `message_len > 0`;
 * `tag`, when non-null, must be valid for reads of `DSTU_AUTH_TAG_BYTES` bytes.
 */

DstuStatus dstu_auth_verify(const DstuAuthKey *key,
                            const uint8_t *message,
                            size_t message_len,
                            const uint8_t *tag);

/**
 * Generates a fresh secret key from the OS CSPRNG. Returns `DSTU_OK` (writing `*out`) or
 * `DSTU_ERR_RANDOM`/`DSTU_ERR_NULL_POINTER`.
 *
 * # Safety
 *
 * `out` must be a valid, non-null pointer to a `*mut DstuBox512SecretKey`.
 */
 DstuStatus dstu_box512_secretkey_generate(DstuBox512SecretKey **out);

/**
 * Builds a secret key from a big-endian `DSTU_BOX512_SECRETKEY_BYTES`-byte scalar. Returns
 * `DSTU_ERR_INVALID_KEY` if it's outside the valid range `{2, ..., n-2}`,
 * `DSTU_ERR_NULL_POINTER` if `bytes`/`out` is NULL.
 *
 * # Safety
 *
 * `bytes` must be valid for reads of `DSTU_BOX512_SECRETKEY_BYTES` bytes when non-null; `out`
 * must be a valid, non-null pointer to a `*mut DstuBox512SecretKey`.
 */
 DstuStatus dstu_box512_secretkey_from_bytes(const uint8_t *bytes, DstuBox512SecretKey **out);

/**
 * Copies the key's big-endian `DSTU_BOX512_SECRETKEY_BYTES`-byte encoding into `out`. **The
 * caller must `dstu_memzero()` this once done** - same gap `dstu_box_secretkey_bytes` has. A NULL
 * `key`/`out` is a no-op.
 *
 * # Safety
 *
 * `out` must be valid for writes of `DSTU_BOX512_SECRETKEY_BYTES` bytes when non-null.
 */
 void dstu_box512_secretkey_bytes(const DstuBox512SecretKey *key, uint8_t *out);

/**
 * Derives the public key for `key` - infallible. Returns NULL if `key` is NULL.
 *
 * # Safety
 *
 * `key` must be either NULL or a valid pointer from `dstu_box512_secretkey_generate`/
 * `dstu_box512_secretkey_from_bytes`.
 */
 DstuBox512PublicKey *dstu_box512_secretkey_public_key(const DstuBox512SecretKey *key);

/**
 * Frees a secret key. NULL is a no-op.
 *
 * # Safety
 *
 * `key` must be either NULL or a pointer previously returned by `dstu_box512_secretkey_generate`/
 * `dstu_box512_secretkey_from_bytes`, not already freed - freeing an already-freed pointer is undefined behavior, not merely unsupported; this fn cannot detect or reject it.
 */

void dstu_box512_secretkey_free(DstuBox512SecretKey *key);

/**
 * Builds a public key from its compressed `DSTU_BOX512_PUBLICKEY_BYTES`-byte `x`-coordinate
 * encoding (`crypto_box512`'s own module doc explains why `x` alone is a safe compression).
 * Returns `DSTU_ERR_INVALID_KEY` if `bytes` isn't a valid field element, or doesn't reconstruct to
 * a point inside the base point's own prime-order subgroup; `DSTU_ERR_NULL_POINTER` if
 * `bytes`/`out` is NULL.
 *
 * # Safety
 *
 * `bytes` must be valid for reads of `DSTU_BOX512_PUBLICKEY_BYTES` bytes when non-null; `out`
 * must be a valid, non-null pointer to a `*mut DstuBox512PublicKey`.
 */
 DstuStatus dstu_box512_publickey_from_bytes(const uint8_t *bytes, DstuBox512PublicKey **out);

/**
 * Copies the key's `DSTU_BOX512_PUBLICKEY_BYTES`-byte encoding into `out` - not secret, no
 * `dstu_memzero` needed afterward. A NULL `key`/`out` is a no-op.
 *
 * # Safety
 *
 * `out` must be valid for writes of `DSTU_BOX512_PUBLICKEY_BYTES` bytes when non-null.
 */
 void dstu_box512_publickey_bytes(const DstuBox512PublicKey *key, uint8_t *out);

/**
 * Frees a public key. NULL is a no-op.
 *
 * # Safety
 *
 * `key` must be either NULL or a pointer previously returned by
 * `dstu_box512_secretkey_public_key`/`dstu_box512_publickey_from_bytes`, not already freed - freeing an already-freed pointer is undefined behavior, not merely unsupported; this fn cannot detect or reject it.
 */

void dstu_box512_publickey_free(DstuBox512PublicKey *key);

/**
 * Encrypts `message` (any length) to `recipient`, drawing a fresh random seed and ephemeral key
 * internally - **not memory-bounded**, same caveat as `crypto_box`'s own `dstu_box_seal`: the
 * whole message is read from `message`/held in `sealed_out`, never chunked. `sealed_out` must
 * have capacity >= `message_len + DSTU_BOX512_SEAL_OVERHEAD` - checked before any crypto work
 * runs; `DSTU_ERR_BUFFER_TOO_SMALL` if not. On `DSTU_OK`, `*sealed_len_out == message_len +
 * DSTU_BOX512_SEAL_OVERHEAD` exactly.
 *
 * # Safety
 *
 * `recipient`/`sealed_len_out` must be non-null; `message` must be valid for reads of
 * `message_len` bytes when non-null and `message_len > 0`; `sealed_out` must be valid for writes
 * of `sealed_out_cap` bytes when non-null.
 */

DstuStatus dstu_box512_seal(const DstuBox512PublicKey *recipient,
                            const uint8_t *message,
                            size_t message_len,
                            uint8_t *sealed_out,
                            size_t sealed_out_cap,
                            size_t *sealed_len_out);

/**
 * Decrypts `sealed` (as produced by [`dstu_box512_seal`]) under `secret` - **not
 * memory-bounded**, same caveat as [`dstu_box512_seal`]. `sealed_len < DSTU_BOX512_SEAL_OVERHEAD`
 * -> `DSTU_ERR_TRUNCATED`. `plaintext_out` must have capacity >= `sealed_len -
 * DSTU_BOX512_SEAL_OVERHEAD` - checked before any crypto work runs; `DSTU_ERR_BUFFER_TOO_SMALL` if
 * not. On `DSTU_OK`, `*plaintext_len_out == sealed_len - DSTU_BOX512_SEAL_OVERHEAD` exactly. On
 * `DSTU_ERR_TAG_MISMATCH` (wrong key, or any tampered wire segment - deliberately not
 * distinguished further, see this module's own top doc comment), `plaintext_out` is left zeroed,
 * never partially-trusted plaintext.
 *
 * # Safety
 *
 * `secret`/`plaintext_len_out` must be non-null; `sealed` must be valid for reads of
 * `sealed_len` bytes when non-null and `sealed_len > 0`; `plaintext_out` must be valid for
 * writes of `plaintext_out_cap` bytes when non-null.
 */

DstuStatus dstu_box512_open(const DstuBox512SecretKey *secret,
                            const uint8_t *sealed,
                            size_t sealed_len,
                            uint8_t *plaintext_out,
                            size_t plaintext_out_cap,
                            size_t *plaintext_len_out);

/**
 * Generates a fresh secret key from the OS CSPRNG. Returns `DSTU_OK` (writing `*out`) or
 * `DSTU_ERR_RANDOM`/`DSTU_ERR_NULL_POINTER`.
 *
 * # Safety
 *
 * `out` must be a valid, non-null pointer to a `*mut DstuBoxSecretKey`.
 */
 DstuStatus dstu_box_secretkey_generate(DstuBoxSecretKey **out);

/**
 * Builds a secret key from a big-endian `DSTU_BOX_SECRETKEY_BYTES`-byte scalar. Returns
 * `DSTU_ERR_INVALID_KEY` if it's outside the valid range `{2, ..., n-2}`,
 * `DSTU_ERR_NULL_POINTER` if `bytes`/`out` is NULL.
 *
 * # Safety
 *
 * `bytes` must be valid for reads of `DSTU_BOX_SECRETKEY_BYTES` bytes when non-null; `out` must
 * be a valid, non-null pointer to a `*mut DstuBoxSecretKey`.
 */
 DstuStatus dstu_box_secretkey_from_bytes(const uint8_t *bytes, DstuBoxSecretKey **out);

/**
 * Copies the key's big-endian `DSTU_BOX_SECRETKEY_BYTES`-byte encoding into `out`. **The caller
 * must `dstu_memzero()` this once done** - same gap `dstu_sign_key_bytes` has, this copies secret
 * material into a caller-owned buffer the wrapped `SecretKey`'s own `Zeroize`-on-`Drop` impl
 * cannot reach. A NULL `key`/`out` is a no-op.
 *
 * # Safety
 *
 * `out` must be valid for writes of `DSTU_BOX_SECRETKEY_BYTES` bytes when non-null.
 */
 void dstu_box_secretkey_bytes(const DstuBoxSecretKey *key, uint8_t *out);

/**
 * Derives the public key for `key` - infallible. Returns NULL if `key` is NULL.
 *
 * # Safety
 *
 * `key` must be either NULL or a valid pointer from `dstu_box_secretkey_generate`/
 * `dstu_box_secretkey_from_bytes`.
 */
 DstuBoxPublicKey *dstu_box_secretkey_public_key(const DstuBoxSecretKey *key);

/**
 * Frees a secret key. NULL is a no-op.
 *
 * # Safety
 *
 * `key` must be either NULL or a pointer previously returned by `dstu_box_secretkey_generate`/
 * `dstu_box_secretkey_from_bytes`, not already freed - freeing an already-freed pointer is undefined behavior, not merely unsupported; this fn cannot detect or reject it.
 */

void dstu_box_secretkey_free(DstuBoxSecretKey *key);

/**
 * Builds a public key from its compressed `DSTU_BOX_PUBLICKEY_BYTES`-byte `x`-coordinate
 * encoding (`crypto_box`'s own module doc explains why `x` alone is a safe compression). Returns
 * `DSTU_ERR_INVALID_KEY` if `bytes` isn't a valid field element, or doesn't reconstruct to a
 * point inside the base point's own prime-order subgroup; `DSTU_ERR_NULL_POINTER` if
 * `bytes`/`out` is NULL.
 *
 * # Safety
 *
 * `bytes` must be valid for reads of `DSTU_BOX_PUBLICKEY_BYTES` bytes when non-null; `out` must
 * be a valid, non-null pointer to a `*mut DstuBoxPublicKey`.
 */
 DstuStatus dstu_box_publickey_from_bytes(const uint8_t *bytes, DstuBoxPublicKey **out);

/**
 * Copies the key's `DSTU_BOX_PUBLICKEY_BYTES`-byte encoding into `out` - not secret, no
 * `dstu_memzero` needed afterward. A NULL `key`/`out` is a no-op.
 *
 * # Safety
 *
 * `out` must be valid for writes of `DSTU_BOX_PUBLICKEY_BYTES` bytes when non-null.
 */
 void dstu_box_publickey_bytes(const DstuBoxPublicKey *key, uint8_t *out);

/**
 * Frees a public key. NULL is a no-op.
 *
 * # Safety
 *
 * `key` must be either NULL or a pointer previously returned by `dstu_box_secretkey_public_key`/
 * `dstu_box_publickey_from_bytes`, not already freed - freeing an already-freed pointer is undefined behavior, not merely unsupported; this fn cannot detect or reject it.
 */

void dstu_box_publickey_free(DstuBoxPublicKey *key);

/**
 * Encrypts `message` (any length) to `recipient`, drawing a fresh random seed and ephemeral key
 * internally - **not memory-bounded**, matching `uacrypt box-seal`'s own documented limitation
 * (D-42/D-169): the whole message is read from `message`/held in `sealed_out`, never chunked.
 * `sealed_out` must have capacity >= `message_len + DSTU_BOX_SEAL_OVERHEAD` - checked before any
 * crypto work runs; `DSTU_ERR_BUFFER_TOO_SMALL` if not. On `DSTU_OK`,
 * `*sealed_len_out == message_len + DSTU_BOX_SEAL_OVERHEAD` exactly.
 *
 * # Safety
 *
 * `recipient`/`sealed_len_out` must be non-null; `message` must be valid for reads of
 * `message_len` bytes when non-null and `message_len > 0`; `sealed_out` must be valid for writes
 * of `sealed_out_cap` bytes when non-null.
 */

DstuStatus dstu_box_seal(const DstuBoxPublicKey *recipient,
                         const uint8_t *message,
                         size_t message_len,
                         uint8_t *sealed_out,
                         size_t sealed_out_cap,
                         size_t *sealed_len_out);

/**
 * Decrypts `sealed` (as produced by [`dstu_box_seal`]) under `secret` - **not memory-bounded**,
 * same caveat as [`dstu_box_seal`]. `sealed_len < DSTU_BOX_SEAL_OVERHEAD` ->
 * `DSTU_ERR_TRUNCATED`. `plaintext_out` must have capacity >= `sealed_len -
 * DSTU_BOX_SEAL_OVERHEAD` - checked before any crypto work runs; `DSTU_ERR_BUFFER_TOO_SMALL` if
 * not. On `DSTU_OK`, `*plaintext_len_out == sealed_len - DSTU_BOX_SEAL_OVERHEAD` exactly. On
 * `DSTU_ERR_TAG_MISMATCH` (wrong key, or any tampered wire segment - deliberately not
 * distinguished further, see this module's own top doc comment), `plaintext_out` is left zeroed,
 * never partially-trusted plaintext.
 *
 * # Safety
 *
 * `secret`/`plaintext_len_out` must be non-null; `sealed` must be valid for reads of
 * `sealed_len` bytes when non-null and `sealed_len > 0`; `plaintext_out` must be valid for
 * writes of `plaintext_out_cap` bytes when non-null.
 */

DstuStatus dstu_box_open(const DstuBoxSecretKey *secret,
                         const uint8_t *sealed,
                         size_t sealed_len,
                         uint8_t *plaintext_out,
                         size_t plaintext_out_cap,
                         size_t *plaintext_len_out);

/**
 * One-shot Kupyna-256 digest of `message`. A NULL `message` with `message_len > 0`, or a NULL
 * `out`, is a no-op.
 *
 * # Safety
 *
 * `message` must be valid for reads of `message_len` bytes when non-null and `message_len > 0`;
 * `out` must be valid for writes of `DSTU_GENERICHASH_256_BYTES` bytes when non-null.
 */
 void dstu_generichash_256(const uint8_t *message, size_t message_len, uint8_t *out);

/**
 * One-shot Kupyna-512 digest of `message`. Same null/zero-length convention as
 * [`dstu_generichash_256`].
 *
 * # Safety
 *
 * `message` must be valid for reads of `message_len` bytes when non-null and `message_len > 0`;
 * `out` must be valid for writes of `DSTU_GENERICHASH_512_BYTES` bytes when non-null.
 */
 void dstu_generichash_512(const uint8_t *message, size_t message_len, uint8_t *out);

/**
 * Creates a new streaming hasher - infallible.
 */
 DstuKupyna256Hasher *dstu_kupyna256_hasher_new(void);

/**
 * Feeds `data` into the hasher. A no-op if `hasher` is NULL, already finalized, or `data` is NULL
 * with `len > 0`.
 *
 * # Safety
 *
 * `hasher` must be a valid, non-null pointer from `dstu_kupyna256_hasher_new`; `data` must be
 * valid for reads of `len` bytes when non-null and `len > 0`.
 */
 void dstu_kupyna256_hasher_update(DstuKupyna256Hasher *hasher, const uint8_t *data, size_t len);

/**
 * Consumes the hasher's accumulated state into `out`. Returns `DSTU_OK`, `DSTU_ERR_FINALIZED` if
 * already finalized, or `DSTU_ERR_NULL_POINTER`.
 *
 * # Safety
 *
 * `hasher` must be a valid, non-null pointer from `dstu_kupyna256_hasher_new`; `out` must be
 * valid for writes of `DSTU_GENERICHASH_256_BYTES` bytes when non-null.
 */
 DstuStatus dstu_kupyna256_hasher_finalize(DstuKupyna256Hasher *hasher, uint8_t *out);

/**
 * Frees a hasher (finalized or not). NULL is a no-op.
 *
 * # Safety
 *
 * `hasher` must be either NULL or a pointer previously returned by `dstu_kupyna256_hasher_new`,
 * not already freed - freeing an already-freed pointer is undefined behavior, not merely unsupported; this fn cannot detect or reject it.
 */

void dstu_kupyna256_hasher_free(DstuKupyna256Hasher *hasher);

/**
 * Creates a new streaming hasher - infallible.
 */
 DstuKupyna512Hasher *dstu_kupyna512_hasher_new(void);

/**
 * Feeds `data` into the hasher. Same convention as [`dstu_kupyna256_hasher_update`].
 *
 * # Safety
 *
 * `hasher` must be a valid, non-null pointer from `dstu_kupyna512_hasher_new`; `data` must be
 * valid for reads of `len` bytes when non-null and `len > 0`.
 */
 void dstu_kupyna512_hasher_update(DstuKupyna512Hasher *hasher, const uint8_t *data, size_t len);

/**
 * Consumes the hasher's accumulated state into `out`. Same convention as
 * [`dstu_kupyna256_hasher_finalize`].
 *
 * # Safety
 *
 * `hasher` must be a valid, non-null pointer from `dstu_kupyna512_hasher_new`; `out` must be
 * valid for writes of `DSTU_GENERICHASH_512_BYTES` bytes when non-null.
 */
 DstuStatus dstu_kupyna512_hasher_finalize(DstuKupyna512Hasher *hasher, uint8_t *out);

/**
 * Frees a hasher (finalized or not). NULL is a no-op.
 *
 * # Safety
 *
 * `hasher` must be either NULL or a pointer previously returned by `dstu_kupyna512_hasher_new`,
 * not already freed - freeing an already-freed pointer is undefined behavior, not merely unsupported; this fn cannot detect or reject it.
 */

void dstu_kupyna512_hasher_free(DstuKupyna512Hasher *hasher);

/**
 * Generates a fresh master key from the OS CSPRNG. Returns `DSTU_OK` (writing `*out`) or
 * `DSTU_ERR_RANDOM`/`DSTU_ERR_NULL_POINTER`.
 *
 * # Safety
 *
 * `out` must be a valid, non-null pointer to a `*mut DstuKdfMasterKey`.
 */
 DstuStatus dstu_kdf_master_key_generate(DstuKdfMasterKey **out);

/**
 * Builds a master key from exactly `DSTU_KDF_KEY_BYTES` bytes. Infallible for a correct call;
 * returns NULL if `key` is NULL.
 *
 * # Safety
 *
 * `key` must be valid for reads of `DSTU_KDF_KEY_BYTES` bytes when non-null.
 */
 DstuKdfMasterKey *dstu_kdf_master_key_from_bytes(const uint8_t *key);

/**
 * Copies the master key's `DSTU_KDF_KEY_BYTES`-byte encoding into `out`. A NULL `key`/`out` is a
 * no-op.
 *
 * # Safety
 *
 * `out` must be valid for writes of `DSTU_KDF_KEY_BYTES` bytes when non-null.
 */
 void dstu_kdf_master_key_bytes(const DstuKdfMasterKey *key, uint8_t *out);

/**
 * Frees a master key. NULL is a no-op.
 *
 * # Safety
 *
 * `key` must be either NULL or a pointer previously returned by `dstu_kdf_master_key_generate`/
 * `dstu_kdf_master_key_from_bytes`, not already freed - freeing an already-freed pointer is undefined behavior, not merely unsupported; this fn cannot detect or reject it.
 */

void dstu_kdf_master_key_free(DstuKdfMasterKey *key);

/**
 * Derives a subkey from `key`/`subkey_id`/`context` - infallible. A NULL `key`/`context`/`out` is
 * a no-op (leaves `out` unwritten).
 *
 * # Safety
 *
 * `context` must be valid for reads of `DSTU_KDF_CONTEXT_BYTES` bytes when non-null; `out` must
 * be valid for writes of `DSTU_KDF_SUBKEY_BYTES` bytes when non-null.
 */

void dstu_kdf_derive_subkey(const DstuKdfMasterKey *key,
                            uint64_t subkey_id,
                            const uint8_t *context,
                            uint8_t *out);

/**
 * Hashes `password` into a NUL-terminated PHC string written to `out` (a caller-owned buffer of
 * at least `DSTU_PWHASH_STRBYTES` bytes). Returns `DSTU_ERR_RANDOM` if the OS CSPRNG fails,
 * `DSTU_ERR_HASH_ERROR` on an internal Argon2/PHC-encoding failure (not expected in practice for
 * this module's own fixed-length salt), or `DSTU_ERR_NULL_POINTER`.
 *
 * # Safety
 *
 * `password` must be valid for reads of `password_len` bytes when non-null and
 * `password_len > 0`; `out` must be valid for writes of `DSTU_PWHASH_STRBYTES` bytes when
 * non-null.
 */

DstuStatus dstu_pwhash_hash_password(const uint8_t *password,
                                     size_t password_len,
                                     DstuPwhashStrength strength,
                                     char *out);

/**
 * Verifies `password` against a NUL-terminated PHC string `hash` (as produced by
 * `dstu_pwhash_hash_password`). Returns `false` for a wrong password, a malformed/unparseable
 * hash string, or a NULL `hash`/malformed-UTF-8 `hash` - matches the wrapped Rust function's own
 * single pass/fail return, nothing for a caller to mishandle by branching differently on the
 * failure cases.
 *
 * # Safety
 *
 * `password` must be valid for reads of `password_len` bytes when non-null and
 * `password_len > 0`; `hash`, when non-null, must point to a valid NUL-terminated C string.
 */
 bool dstu_pwhash_verify_password(const uint8_t *password, size_t password_len, const char *hash);

/**
 * Fills `buf[0..len]` with cryptographically secure random bytes from the OS CSPRNG.
 *
 * Returns `DSTU_OK`, or `DSTU_ERR_RANDOM` if the OS CSPRNG fails. `DSTU_ERR_NULL_POINTER` if
 * `buf` is NULL while `len > 0`; `len == 0` is a no-op success regardless of `buf`.
 *
 * # Safety
 *
 * `buf` must be valid for writes of `len` bytes when non-null and `len > 0`.
 */
 DstuStatus dstu_randombytes_buf(uint8_t *buf, size_t len);

/**
 * Generates a fresh key from the OS CSPRNG. Returns `DSTU_OK` (writing `*out`) or
 * `DSTU_ERR_RANDOM`/`DSTU_ERR_NULL_POINTER`.
 *
 * # Safety
 *
 * `out` must be a valid, non-null pointer to a `*mut DstuSecretboxKey`.
 */
 DstuStatus dstu_secretbox_key_generate(DstuSecretboxKey **out);

/**
 * Builds a key from exactly `DSTU_SECRETBOX_KEY_BYTES` bytes. Infallible for a correct call;
 * returns NULL if `key` is NULL.
 *
 * # Safety
 *
 * `key` must be valid for reads of `DSTU_SECRETBOX_KEY_BYTES` bytes when non-null.
 */
 DstuSecretboxKey *dstu_secretbox_key_from_bytes(const uint8_t *key);

/**
 * Copies the key's `DSTU_SECRETBOX_KEY_BYTES`-byte encoding into `out`. A NULL `key`/`out` is a
 * no-op.
 *
 * # Safety
 *
 * `out` must be valid for writes of `DSTU_SECRETBOX_KEY_BYTES` bytes when non-null.
 */
 void dstu_secretbox_key_bytes(const DstuSecretboxKey *key, uint8_t *out);

/**
 * Frees a key. NULL is a no-op.
 *
 * # Safety
 *
 * `key` must be either NULL or a pointer previously returned by `dstu_secretbox_key_generate`/
 * `dstu_secretbox_key_from_bytes`, not already freed - freeing an already-freed pointer is undefined behavior, not merely unsupported; this fn cannot detect or reject it.
 */

void dstu_secretbox_key_free(DstuSecretboxKey *key);

/**
 * Encrypts and authenticates `plaintext` under `key`, drawing a fresh random nonce internally.
 * `sealed_out` must have capacity >= `plaintext_len + DSTU_SECRETBOX_OVERHEAD` - checked before
 * any crypto work runs; `DSTU_ERR_BUFFER_TOO_SMALL` if not. On `DSTU_OK`,
 * `*sealed_len_out == plaintext_len + DSTU_SECRETBOX_OVERHEAD` exactly.
 *
 * # Safety
 *
 * `key`/`sealed_len_out` must be non-null; `plaintext` must be valid for reads of
 * `plaintext_len` bytes when non-null and `plaintext_len > 0`; `sealed_out` must be valid for
 * writes of `sealed_out_cap` bytes when non-null.
 */

DstuStatus dstu_secretbox_seal(const DstuSecretboxKey *key,
                               const uint8_t *plaintext,
                               size_t plaintext_len,
                               uint8_t *sealed_out,
                               size_t sealed_out_cap,
                               size_t *sealed_len_out);

/**
 * Verifies and decrypts `sealed` (as produced by [`dstu_secretbox_seal`]) under `key`.
 * `sealed_len < DSTU_SECRETBOX_OVERHEAD` -> `DSTU_ERR_TRUNCATED`. `plaintext_out` must have
 * capacity >= `sealed_len - DSTU_SECRETBOX_OVERHEAD` - checked before any crypto work runs;
 * `DSTU_ERR_BUFFER_TOO_SMALL` if not. On `DSTU_OK`,
 * `*plaintext_len_out == sealed_len - DSTU_SECRETBOX_OVERHEAD` exactly. On
 * `DSTU_ERR_TAG_MISMATCH`, `plaintext_out` is left zeroed, never partially-trusted plaintext.
 *
 * # Safety
 *
 * `key`/`plaintext_len_out` must be non-null; `sealed` must be valid for reads of `sealed_len`
 * bytes when non-null and `sealed_len > 0`; `plaintext_out` must be valid for writes of
 * `plaintext_out_cap` bytes when non-null.
 */

DstuStatus dstu_secretbox_open(const DstuSecretboxKey *key,
                               const uint8_t *sealed,
                               size_t sealed_len,
                               uint8_t *plaintext_out,
                               size_t plaintext_out_cap,
                               size_t *plaintext_len_out);

/**
 * Generates a fresh key from the OS CSPRNG. Returns `DSTU_OK` (writing `*out`) or
 * `DSTU_ERR_RANDOM`/`DSTU_ERR_NULL_POINTER`.
 *
 * # Safety
 *
 * `out` must be a valid, non-null pointer to a `*mut DstuSecretstreamKey`.
 */
 DstuStatus dstu_secretstream_key_generate(DstuSecretstreamKey **out);

/**
 * Builds a key from exactly `DSTU_SECRETSTREAM_KEY_BYTES` bytes. Infallible for a correct call;
 * returns NULL if `key` is NULL.
 *
 * # Safety
 *
 * `key` must be valid for reads of `DSTU_SECRETSTREAM_KEY_BYTES` bytes when non-null.
 */
 DstuSecretstreamKey *dstu_secretstream_key_from_bytes(const uint8_t *key);

/**
 * Copies the key's `DSTU_SECRETSTREAM_KEY_BYTES`-byte encoding into `out`. A NULL `key`/`out` is
 * a no-op.
 *
 * # Safety
 *
 * `out` must be valid for writes of `DSTU_SECRETSTREAM_KEY_BYTES` bytes when non-null.
 */
 void dstu_secretstream_key_bytes(const DstuSecretstreamKey *key, uint8_t *out);

/**
 * Frees a key. NULL is a no-op.
 *
 * # Safety
 *
 * `key` must be either NULL or a pointer previously returned by
 * `dstu_secretstream_key_generate`/`dstu_secretstream_key_from_bytes`, not already freed - freeing an already-freed pointer is undefined behavior, not merely unsupported; this fn cannot detect or reject it.
 */

void dstu_secretstream_key_free(DstuSecretstreamKey *key);

/**
 * Starts a new stream under `key`, drawing a fresh random header and writing it to `header_out`.
 * Returns `DSTU_OK` (writing `*out`/`header_out`), `DSTU_ERR_RANDOM`, or
 * `DSTU_ERR_NULL_POINTER`.
 *
 * # Safety
 *
 * `key`/`out` must be non-null; `header_out` must be valid for writes of
 * `DSTU_SECRETSTREAM_HEADER_BYTES` bytes when non-null.
 */

DstuStatus dstu_secretstream_push_init(const DstuSecretstreamKey *key,
                                       DstuPushState **out,
                                       uint8_t *header_out);

/**
 * Returns whether this push state has already emitted a `Tag::Final` chunk. A NULL `state`
 * reports `false` (arbitrary but safe - there is no distinct "invalid handle" outcome for a
 * plain `bool` return).
 *
 * # Safety
 *
 * `state` must be either NULL or a valid pointer from `dstu_secretstream_push_init`.
 */
 bool dstu_secretstream_push_is_finalized(const DstuPushState *state);

/**
 * Encrypts one chunk. `ciphertext_out_len` must equal `plaintext_len` exactly -
 * `DSTU_ERR_INVALID_LENGTH` otherwise. `DSTU_ERR_FINALIZED` if a previous chunk already used
 * `DSTU_TAG_FINAL`.
 *
 * # Safety
 *
 * `state`/`tag_out` must be non-null; `plaintext` must be valid for reads of `plaintext_len`
 * bytes when non-null and `plaintext_len > 0`; `ciphertext_out` must be valid for writes of
 * `ciphertext_out_len` bytes when non-null and `ciphertext_out_len > 0`; `tag_out` must be valid
 * for writes of `DSTU_SECRETSTREAM_TAG_BYTES` bytes.
 */

DstuStatus dstu_secretstream_push(DstuPushState *state,
                                  DstuTag tag,
                                  const uint8_t *plaintext,
                                  size_t plaintext_len,
                                  uint8_t *ciphertext_out,
                                  size_t ciphertext_out_len,
                                  uint8_t *tag_out);

/**
 * Frees a push state. NULL is a no-op.
 *
 * # Safety
 *
 * `state` must be either NULL or a pointer previously returned by
 * `dstu_secretstream_push_init`, not already freed - freeing an already-freed pointer is undefined behavior, not merely unsupported; this fn cannot detect or reject it.
 */

void dstu_secretstream_push_free(DstuPushState *state);

/**
 * Re-derives the stream's initial subkey from `key` and `header` (as produced by
 * `dstu_secretstream_push_init`) - infallible. Returns NULL if `key`/`header` is NULL.
 *
 * # Safety
 *
 * `key` must be valid when non-null; `header` must be valid for reads of
 * `DSTU_SECRETSTREAM_HEADER_BYTES` bytes when non-null.
 */
 DstuPullState *dstu_secretstream_pull_init(const DstuSecretstreamKey *key, const uint8_t *header);

/**
 * Returns whether this pull state has already consumed a `Tag::Final` chunk. Same NULL
 * convention as [`dstu_secretstream_push_is_finalized`].
 *
 * # Safety
 *
 * `state` must be either NULL or a valid pointer from `dstu_secretstream_pull_init`.
 */
 bool dstu_secretstream_pull_is_finalized(const DstuPullState *state);

/**
 * Verifies and decrypts one chunk. `plaintext_out_len` must equal `ciphertext_len` exactly -
 * `DSTU_ERR_INVALID_LENGTH` otherwise. `DSTU_ERR_UNKNOWN_TAG` if `tag_byte` isn't 0-3,
 * `DSTU_ERR_FINALIZED` if already finalized, `DSTU_ERR_TAG_MISMATCH` on auth failure
 * (`plaintext_out` left zeroed). On `DSTU_OK`, `*tag_out` holds the authenticated tag.
 *
 * # Safety
 *
 * `state`/`auth_tag`/`tag_out` must be non-null; `ciphertext` must be valid for reads of
 * `ciphertext_len` bytes when non-null and `ciphertext_len > 0`; `auth_tag` must be valid for
 * reads of `DSTU_SECRETSTREAM_TAG_BYTES` bytes; `plaintext_out` must be valid for writes of
 * `plaintext_out_len` bytes when non-null and `plaintext_out_len > 0`.
 */

DstuStatus dstu_secretstream_pull(DstuPullState *state,
                                  uint8_t tag_byte,
                                  const uint8_t *ciphertext,
                                  size_t ciphertext_len,
                                  const uint8_t *auth_tag,
                                  uint8_t *plaintext_out,
                                  size_t plaintext_out_len,
                                  DstuTag *tag_out);

/**
 * Frees a pull state. NULL is a no-op.
 *
 * # Safety
 *
 * `state` must be either NULL or a pointer previously returned by
 * `dstu_secretstream_pull_init`, not already freed - freeing an already-freed pointer is undefined behavior, not merely unsupported; this fn cannot detect or reject it.
 */

void dstu_secretstream_pull_free(DstuPullState *state);

/**
 * Re-verifies one official test vector per primitive (Kalyna, Kupyna, Strumok, DSTU 4145)
 * against the live compiled build. Returns `DSTU_OK` on success, `DSTU_ERR_SELFTEST_FAILED`
 * otherwise.
 */
 DstuStatus dstu_selftest(void);

/**
 * Generates a fresh signing key from the OS CSPRNG. Returns `DSTU_OK` (writing `*out`) or
 * `DSTU_ERR_RANDOM`/`DSTU_ERR_NULL_POINTER`.
 *
 * # Safety
 *
 * `out` must be a valid, non-null pointer to a `*mut DstuSigningKey`.
 */
 DstuStatus dstu_sign_key_generate(DstuSigningKey **out);

/**
 * Builds a signing key from a big-endian `DSTU_SIGN_PRIVATE_KEY_BYTES`-byte scalar `d`. Returns
 * `DSTU_ERR_INVALID_KEY` if `d` is zero or >= the curve order, `DSTU_ERR_NULL_POINTER` if `d`/
 * `out` is NULL.
 *
 * # Safety
 *
 * `d` must be valid for reads of `DSTU_SIGN_PRIVATE_KEY_BYTES` bytes when non-null; `out` must
 * be a valid, non-null pointer to a `*mut DstuSigningKey`.
 */
 DstuStatus dstu_sign_key_from_bytes(const uint8_t *d, DstuSigningKey **out);

/**
 * Copies `d`'s big-endian `DSTU_SIGN_PRIVATE_KEY_BYTES`-byte encoding into `out`. **The caller
 * must `dstu_memzero()` this once done** - this function copies secret material into a
 * caller-owned buffer the wrapped `SigningKey`'s own `Zeroize`-on-`Drop` impl cannot reach. A
 * NULL `key`/`out` is a no-op.
 *
 * # Safety
 *
 * `out` must be valid for writes of `DSTU_SIGN_PRIVATE_KEY_BYTES` bytes when non-null.
 */
 void dstu_sign_key_bytes(const DstuSigningKey *key, uint8_t *out);

/**
 * Frees a signing key. NULL is a no-op.
 *
 * # Safety
 *
 * `key` must be either NULL or a pointer previously returned by `dstu_sign_key_generate`/
 * `dstu_sign_key_from_bytes`, not already freed - freeing an already-freed pointer is undefined behavior, not merely unsupported; this fn cannot detect or reject it.
 */

void dstu_sign_key_free(DstuSigningKey *key);

/**
 * Derives the public verifying key for `key` - infallible. Returns NULL if `key` is NULL.
 *
 * # Safety
 *
 * `key` must be either NULL or a valid pointer from `dstu_sign_key_generate`/
 * `dstu_sign_key_from_bytes`.
 */
 DstuVerifyingKey *dstu_sign_verifying_key(const DstuSigningKey *key);

/**
 * Copies the key's plain `x || y` `DSTU_SIGN_PUBLIC_KEY_BYTES`-byte encoding into `out`
 * (**not** the DSTU 4145 standard's own compressed point encoding - see the wrapped Rust
 * module's own doc comment). A NULL `key`/`out` is a no-op.
 *
 * # Safety
 *
 * `out` must be valid for writes of `DSTU_SIGN_PUBLIC_KEY_BYTES` bytes when non-null.
 */
 void dstu_verifying_key_to_bytes(const DstuVerifyingKey *key, uint8_t *out);

/**
 * Builds a verifying key from `DSTU_SIGN_PUBLIC_KEY_BYTES` bytes of plain `x || y` encoding -
 * infallible, no validation that the point is actually on the curve (matches the wrapped Rust
 * function's own `from_uncompressed_bytes` convention). Returns NULL if `bytes` is NULL.
 *
 * # Safety
 *
 * `bytes` must be valid for reads of `DSTU_SIGN_PUBLIC_KEY_BYTES` bytes when non-null.
 */
 DstuVerifyingKey *dstu_verifying_key_from_bytes(const uint8_t *bytes);

/**
 * Frees a verifying key. NULL is a no-op.
 *
 * # Safety
 *
 * `key` must be either NULL or a pointer previously returned by `dstu_sign_verifying_key`/
 * `dstu_verifying_key_from_bytes`, not already freed - freeing an already-freed pointer is undefined behavior, not merely unsupported; this fn cannot detect or reject it.
 */

void dstu_verifying_key_free(DstuVerifyingKey *key);

/**
 * Signs `message`, hashing it with Kupyna-256 internally and deriving the ephemeral nonce
 * deterministically - infallible, no RNG dependency. A NULL `key`/`sig_out`, or a NULL `message`
 * with `message_len > 0`, is a no-op.
 *
 * # Safety
 *
 * `message` must be valid for reads of `message_len` bytes when non-null and `message_len > 0`;
 * `sig_out` must be valid for writes of `DSTU_SIGN_SIGNATURE_BYTES` bytes when non-null.
 */

void dstu_sign(const DstuSigningKey *key,
               const uint8_t *message,
               size_t message_len,
               uint8_t *sig_out);

/**
 * Signs an already-computed `DSTU_SIGN_DIGEST_BYTES`-byte Kupyna-256 digest directly - for a
 * message hashed incrementally rather than held whole in memory. Same null-handling convention
 * as [`dstu_sign`].
 *
 * # Safety
 *
 * `digest` must be valid for reads of `DSTU_SIGN_DIGEST_BYTES` bytes when non-null; `sig_out`
 * must be valid for writes of `DSTU_SIGN_SIGNATURE_BYTES` bytes when non-null.
 */
 void dstu_sign_digest(const DstuSigningKey *key, const uint8_t *digest, uint8_t *sig_out);

/**
 * Verifies `sig` over `message` under `key`. Returns `false` for a NULL `key`/`sig` (a misuse
 * case with no distinct code to report through a plain `bool`), a NULL `message` with
 * `message_len > 0`, or an actual verification failure - a signature either verifies or it
 * doesn't, this is the answer either way.
 *
 * # Safety
 *
 * `message` must be valid for reads of `message_len` bytes when non-null and `message_len > 0`;
 * `sig` must be valid for reads of `DSTU_SIGN_SIGNATURE_BYTES` bytes when non-null.
 */

bool dstu_verify(const DstuVerifyingKey *key,
                 const uint8_t *message,
                 size_t message_len,
                 const uint8_t *sig);

/**
 * Verifies `sig` over an already-computed `DSTU_SIGN_DIGEST_BYTES`-byte digest directly. Same
 * null-handling convention as [`dstu_verify`].
 *
 * # Safety
 *
 * `digest` must be valid for reads of `DSTU_SIGN_DIGEST_BYTES` bytes when non-null; `sig` must
 * be valid for reads of `DSTU_SIGN_SIGNATURE_BYTES` bytes when non-null.
 */
 bool dstu_verify_digest(const DstuVerifyingKey *key, const uint8_t *digest, const uint8_t *sig);

/**
 * Generates a fresh signing key from the OS CSPRNG. Returns `DSTU_OK` (writing `*out`) or
 * `DSTU_ERR_RANDOM`/`DSTU_ERR_NULL_POINTER`.
 *
 * # Safety
 *
 * `out` must be a valid, non-null pointer to a `*mut DstuSigningKey257`.
 */
 DstuStatus dstu_sign257_key_generate(DstuSigningKey257 **out);

/**
 * Builds a signing key from a big-endian `DSTU_SIGN257_PRIVATE_KEY_BYTES`-byte scalar `d`.
 * Returns `DSTU_ERR_INVALID_KEY` if `d` is zero or >= the curve order, `DSTU_ERR_NULL_POINTER` if
 * `d`/`out` is NULL.
 *
 * # Safety
 *
 * `d` must be valid for reads of `DSTU_SIGN257_PRIVATE_KEY_BYTES` bytes when non-null; `out` must
 * be a valid, non-null pointer to a `*mut DstuSigningKey257`.
 */
 DstuStatus dstu_sign257_key_from_bytes(const uint8_t *d, DstuSigningKey257 **out);

/**
 * Copies `d`'s big-endian `DSTU_SIGN257_PRIVATE_KEY_BYTES`-byte encoding into `out`. **The caller
 * must `dstu_memzero()` this once done** - same gap `dstu_sign_key_bytes` has. A NULL `key`/`out`
 * is a no-op.
 *
 * # Safety
 *
 * `out` must be valid for writes of `DSTU_SIGN257_PRIVATE_KEY_BYTES` bytes when non-null.
 */
 void dstu_sign257_key_bytes(const DstuSigningKey257 *key, uint8_t *out);

/**
 * Frees a signing key. NULL is a no-op.
 *
 * # Safety
 *
 * `key` must be either NULL or a pointer previously returned by `dstu_sign257_key_generate`/
 * `dstu_sign257_key_from_bytes`, not already freed - freeing an already-freed pointer is undefined behavior, not merely unsupported; this fn cannot detect or reject it.
 */

void dstu_sign257_key_free(DstuSigningKey257 *key);

/**
 * Derives the public verifying key for `key` - infallible. Returns NULL if `key` is NULL.
 *
 * # Safety
 *
 * `key` must be either NULL or a valid pointer from `dstu_sign257_key_generate`/
 * `dstu_sign257_key_from_bytes`.
 */
 DstuVerifyingKey257 *dstu_sign257_verifying_key(const DstuSigningKey257 *key);

/**
 * Copies the key's plain `x || y` `DSTU_SIGN257_PUBLIC_KEY_BYTES`-byte encoding into `out` (not
 * the DSTU 4145 standard's own compressed point encoding - see `crypto_sign`'s own module doc). A
 * NULL `key`/`out` is a no-op.
 *
 * # Safety
 *
 * `out` must be valid for writes of `DSTU_SIGN257_PUBLIC_KEY_BYTES` bytes when non-null.
 */
 void dstu_verifying_key257_to_bytes(const DstuVerifyingKey257 *key, uint8_t *out);

/**
 * Builds a verifying key from `DSTU_SIGN257_PUBLIC_KEY_BYTES` bytes of plain `x || y` encoding -
 * infallible, see this module's own top doc comment for why no on-curve check happens here.
 * Returns NULL if `bytes` is NULL.
 *
 * # Safety
 *
 * `bytes` must be valid for reads of `DSTU_SIGN257_PUBLIC_KEY_BYTES` bytes when non-null.
 */
 DstuVerifyingKey257 *dstu_verifying_key257_from_bytes(const uint8_t *bytes);

/**
 * Frees a verifying key. NULL is a no-op.
 *
 * # Safety
 *
 * `key` must be either NULL or a pointer previously returned by `dstu_sign257_verifying_key`/
 * `dstu_verifying_key257_from_bytes`, not already freed - freeing an already-freed pointer is undefined behavior, not merely unsupported; this fn cannot detect or reject it.
 */

void dstu_verifying_key257_free(DstuVerifyingKey257 *key);

/**
 * Signs `message`, hashing it with Kupyna-256 internally and deriving the ephemeral nonce
 * deterministically - infallible, no RNG dependency. A NULL `key`/`sig_out`, or a NULL `message`
 * with `message_len > 0`, is a no-op.
 *
 * # Safety
 *
 * `message` must be valid for reads of `message_len` bytes when non-null and `message_len > 0`;
 * `sig_out` must be valid for writes of `DSTU_SIGN257_SIGNATURE_BYTES` bytes when non-null.
 */

void dstu_sign257(const DstuSigningKey257 *key,
                  const uint8_t *message,
                  size_t message_len,
                  uint8_t *sig_out);

/**
 * Signs an already-computed `DSTU_SIGN257_DIGEST_BYTES`-byte Kupyna-256 digest directly - for a
 * message hashed incrementally rather than held whole in memory. Same null-handling convention as
 * [`dstu_sign257`].
 *
 * # Safety
 *
 * `digest` must be valid for reads of `DSTU_SIGN257_DIGEST_BYTES` bytes when non-null; `sig_out`
 * must be valid for writes of `DSTU_SIGN257_SIGNATURE_BYTES` bytes when non-null.
 */
 void dstu_sign257_digest(const DstuSigningKey257 *key, const uint8_t *digest, uint8_t *sig_out);

/**
 * Verifies `sig` over `message` under `key`. Returns `false` for a NULL `key`/`sig` (a misuse
 * case with no distinct code to report through a plain `bool`), a NULL `message` with
 * `message_len > 0`, or an actual verification failure.
 *
 * # Safety
 *
 * `message` must be valid for reads of `message_len` bytes when non-null and `message_len > 0`;
 * `sig` must be valid for reads of `DSTU_SIGN257_SIGNATURE_BYTES` bytes when non-null.
 */

bool dstu_verify257(const DstuVerifyingKey257 *key,
                    const uint8_t *message,
                    size_t message_len,
                    const uint8_t *sig);

/**
 * Verifies `sig` over an already-computed `DSTU_SIGN257_DIGEST_BYTES`-byte digest directly. Same
 * null-handling convention as [`dstu_verify257`].
 *
 * # Safety
 *
 * `digest` must be valid for reads of `DSTU_SIGN257_DIGEST_BYTES` bytes when non-null; `sig` must
 * be valid for reads of `DSTU_SIGN257_SIGNATURE_BYTES` bytes when non-null.
 */

bool dstu_verify257_digest(const DstuVerifyingKey257 *key,
                           const uint8_t *digest,
                           const uint8_t *sig);

/**
 * Generates a fresh key from the OS CSPRNG. Returns `DSTU_OK` (writing `*out`) or
 * `DSTU_ERR_RANDOM`/`DSTU_ERR_NULL_POINTER`.
 *
 * # Safety
 *
 * `out` must be a valid, non-null pointer to a `*mut DstuStreamKey`.
 */
 DstuStatus dstu_stream_key_generate(DstuStreamKey **out);

/**
 * Builds a key from exactly `DSTU_STREAM_KEY_BYTES` bytes. Infallible for a correct call;
 * returns NULL if `key` is NULL.
 *
 * # Safety
 *
 * `key` must be valid for reads of `DSTU_STREAM_KEY_BYTES` bytes when non-null.
 */
 DstuStreamKey *dstu_stream_key_from_bytes(const uint8_t *key);

/**
 * Copies the key's `DSTU_STREAM_KEY_BYTES`-byte encoding into `out`. A NULL `key`/`out` is a
 * no-op.
 *
 * # Safety
 *
 * `out` must be valid for writes of `DSTU_STREAM_KEY_BYTES` bytes when non-null.
 */
 void dstu_stream_key_bytes(const DstuStreamKey *key, uint8_t *out);

/**
 * Frees a key. NULL is a no-op.
 *
 * # Safety
 *
 * `key` must be either NULL or a pointer previously returned by `dstu_stream_key_generate`/
 * `dstu_stream_key_from_bytes`, not already freed - freeing an already-freed pointer is undefined behavior, not merely unsupported; this fn cannot detect or reject it.
 */

void dstu_stream_key_free(DstuStreamKey *key);

/**
 * XORs `plaintext` with a fresh keystream under `key`, drawing a random IV internally.
 * `sealed_out` must have capacity >= `plaintext_len + DSTU_STREAM_OVERHEAD` - checked before any
 * crypto work runs; `DSTU_ERR_BUFFER_TOO_SMALL` if not.
 *
 * # Safety
 *
 * `key`/`sealed_len_out` must be non-null; `plaintext` must be valid for reads of
 * `plaintext_len` bytes when non-null and `plaintext_len > 0`; `sealed_out` must be valid for
 * writes of `sealed_out_cap` bytes when non-null.
 */

DstuStatus dstu_stream_encrypt(const DstuStreamKey *key,
                               const uint8_t *plaintext,
                               size_t plaintext_len,
                               uint8_t *sealed_out,
                               size_t sealed_out_cap,
                               size_t *sealed_len_out);

/**
 * Reverses [`dstu_stream_encrypt`]. `sealed_len < DSTU_STREAM_OVERHEAD` -> `DSTU_ERR_TRUNCATED`
 * (the only possible error - there is no tag to fail). `plaintext_out` must have capacity >=
 * `sealed_len - DSTU_STREAM_OVERHEAD` - checked before any work runs; `DSTU_ERR_BUFFER_TOO_SMALL`
 * if not. **Never fails on tampered input** - a modified `sealed` decrypts to different,
 * silently-wrong plaintext, not an error.
 *
 * # Safety
 *
 * `key`/`plaintext_len_out` must be non-null; `sealed` must be valid for reads of `sealed_len`
 * bytes when non-null and `sealed_len > 0`; `plaintext_out` must be valid for writes of
 * `plaintext_out_cap` bytes when non-null.
 */

DstuStatus dstu_stream_decrypt(const DstuStreamKey *key,
                               const uint8_t *sealed,
                               size_t sealed_len,
                               uint8_t *plaintext_out,
                               size_t plaintext_out_cap,
                               size_t *plaintext_len_out);

/**
 * Overwrites `buf[0..len]` with zero bytes, then fences so the compiler cannot optimize the write
 * away as dead (libsodium's `sodium_memzero` equivalent, D-148 point 5's gap-filler): the
 * `Zeroize`-on-`Drop` impls this crate's opaque handles wrap fire automatically on `dstu_*_free`,
 * but a value copied *out* into a caller-owned buffer (e.g. `dstu_sign_key_bytes`) is the
 * caller's own responsibility to wipe once done - this function is how.
 *
 * A NULL `buf` or `len == 0` is a no-op, not an error - there is no `DstuStatus` return here to
 * report one through.
 *
 * # Safety
 *
 * `buf` must be valid for writes of `len` bytes when non-null and `len > 0`.
 */
 void dstu_memzero(void *buf, size_t len);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* DSTU_CORE_H */
