'use strict';

/**
 * Node.js bindings for dstu-core (Ukrainian DSTU cryptographic standards).
 *
 * Not independently audited. See the root project's docs/SECURITY.md and docs/DECISIONS.md for
 * the full threat model and per-construction status (docs/bindings-strategy.md T-50).
 *
 * `../native/index.js` is the napi-rs-generated low-level binding (regenerated by `npm run
 * build`, never hand-edited or committed - see .gitignore). This file is the public package
 * entry point: every native export re-exported as-is, plus the idiomatic
 * `stream.Transform`-based `SecretStreamEncryptor`/`SecretStreamDecryptor` (step 3) layered on
 * top of the native `SecretStreamPushState`/`SecretStreamPullState` (step 2) in pure JS, no new
 * Rust glue - mirrors bindings/python/python/dstu_core/__init__.py's own split exactly.
 */

const native = require('../native/index.js');
const { SecretStreamEncryptor, SecretStreamDecryptor } = require('./secretstream.js');

module.exports = {
  ...native,
  SecretStreamEncryptor,
  SecretStreamDecryptor,
};
